var game = new Phaser.Game('100%', '100%', Phaser.AUTO, '')
// game.state.add('Boot', { preload: preload, create: create, update: update, render: render }, true)
game.state.add('Shallow', shallowState)
game.state.add('Medium', mediumState)
game.state.add('Deep', deepState)
game.state.add('Subdiving', subdivingState)
game.state.start('Shallow')
